#!/usr/bin/env bash

# this is a bootstrapper meant to manage and load individual scripts which
# create a shell prompt

##########################
# Verifying Correct Load #
##########################

if [[ $# -lt 1 ]]; then
	echo "No shell prompt specified, aborting"
	exit 1
fi
if [[ $# -gt 1 ]]; then
	echo "Too many arguments, aborting"
	exit 1
fi

#####################
# Setting Variables #
#####################

__path="${BASH_SOURCE%/*}/"
__file="${__path}$1"

###########################
# Loading a Prompt Script #
###########################

if [[ -f ${__file} ]]; then
	source ${__file}
	exit 0
else
	echo ${__file}
	echo "Invalid prompt file passed, aborting"
	exit 1
fi
