#!/usr/bin/env bash

# opyright (C) 2016-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2016-present Sven Greb <development@svengreb.de>

# Modified By: Bruhulance
# Project:    igloo
# Repository: https://github.com/arcticicestudio/igloo
# License:    MIT
# References:
#   http://stackoverflow.com/questions/19092488/custom-bash-prompt-is-overwriting-itself/19501525#19501528
#   http://mywiki.wooledge.org/BashFAQ/053

# This creates the full PS1 prompt
compile_prompt () {
  local CONNECTBAR_DOWN='┌─'
  local CONNECTBAR_UP='└─'
  local SPLITBAR=' - '
  local LETTERS=($'\u0393' $'\u03b3' $'\u03b4' $'\u03bb' $'\u03bc' $'\u03be' $'\u03c0' $'\u03a3' $'\u03c6' $'\u03c8' $'\u03a9')
  local c_gray='\e[01;30m'
  local c_blue='\e[01;36m'
  local c_cyan='\e[0;34m'
  local c_red='\e[01;31m'
  local c_yellow='\e[01;33m'
  local c_reset='\e[0m'

  # > Connectbar Down
  # Format:
  #   (newline)(bright colors)(connectbar down)
  PS1="\[${c_cyan}\]$CONNECTBAR_DOWN"

  # > Username & Machine Name
  # Format:
  #   (bracket open)(username:hostname)(bracket close)(splitbar)
  PS1+="[\[${c_blue}\]\u\[${c_cyan}\]@\[${c_yellow}\]\H\[${c_cyan}\]]"
  PS1+="$SPLITBAR"

  # > Working Directory
  # Format:
  #   (bracket open)(working directory)(bracket close)(newline)(connectbar up)
  PS1+="[\[${c_blue}\]\w\[${c_cyan}\]]"
  PS1+="$SPLITBAR"

  # > Time Stamp
  # Format:
  #   (bracket open)(timestamp)(bracket close)
  PS1+="[\[${c_blue}\]\@\[${c_cyan}\]]"

  # > Connectbar Up
  PS1+="\n\[${c_cyan}\]$CONNECTBAR_UP"

  # > Choosing a random greek letter
  # NOTE: Color must be escaped with '\[\]' to fix the text overflow bug!
  # Format:
  #   (color reset)(bracket open)(letter)(bracket close)(color reset)
  PS1+="\[${c_reset}\]\[${c_cyan}\]${LETTERS["$[RANDOM % ${#LETTERS[@]}]"]}\[${c_cyan}\] \[\e[0m\]"
}

# Need to execute the function to build PS1 then we echo it out to stdout
# which gets received by the .bashrc and put into PS1 there. Why.
compile_prompt
echo $PS1
